server:
  port: 8080

spring:
  onto:
    path: src/main/resources/TinHoc.owl
    base-uri: http://www.tinhoc.edu.vn
    max-nested-count: 5
    prefix: thoc
  application:
    jwt-secret: TdupoBlZjaeEOQOcIwKgdLdbFQHSnkYR
    jwt-expire: 18000000 #2hours
    media-path: ./media/
    dictionary: ./vietnamese-dictionary.txt
  servlet:
    multipart:
      max-file-size: 1GB
      max-request-size: 1GB

  devtools:
    restart:
      enabled: true
